[env]
TERM = "xterm-256color"

[font]
size = 12.0
# size = 11.0

[font.normal]
# family = "MartianMonoNerdFont"
# family = "Cascadia Code"
family = "Iosevka Term Semibold"

[font.bold]
# family = "Iosevka Term"
# family = "Cascadia Code"
# style = "Bold"

[font.italic]
family = "Iosevka Term"
# style = "Semibold"
# family = "Cascadia Code"

[font.offset]
x = 0
y = 0

[window.padding]
x = 10

[general]
import = ["/home/maru/.config/alacritty/themes/catppuccin-frappe.toml"]
# import = ["/home/maru/.config/alacritty/themes/catppuccin-mocha.toml"]
# import = ["/home/maru/.config/alacritty/themes/catppuccin-frappe.toml"]
# import = ["/home/maru/.config/alacritty/themes/ayu-mirage.toml"]
# import = ["/home/maru/.config/alacritty/themes/everblush.toml"]
# import = ["/home/maru/.config/alacritty/themes/rose-pine-dawn.toml"]
