[colors.primary]
background = "#141b1e"
foreground = "#dadada"

[colors.normal]
black   = "#141b1e"
red     = "#e57474"
green   = "#8ccf7e"
yellow  = "#e5c76b"
blue    = "#67b0e8"
magenta = "#c47fd5"
cyan    = "#6cbfbf"
white   = "#b3b9b8"

[colors.bright]
black   = "#232a2d"
red     = "#f48b8b"
green   = "#a6d78d"
yellow  = "#efd287"
blue    = "#7bbef0"
magenta = "#d99ce3"
cyan    = "#82cfd9"
white   = "#dadada"

[colors.cursor]
text   = "#141b1e"
cursor = "#dadada"
